### ISSUE TITLE
放个gif上来

### ISSUE THREAD

**Issue by fritx** [chunmu/RNMusicPlayer#1]
这个项目的笔记太厉害了，👍
最好能gif动图上来，mac上用这个工具不错

![image](https://cloud.githubusercontent.com/assets/6647633/19308522/962234ec-90b2-11e6-9032-5bd8b7867032.png)

**Comment by chunmu** [comment]
...谢谢亮神 @fritx

**Comment by chunmu** [comment]
今天录制了gif  模拟器感觉效果不太好
